lint:
  files_exist:
    - conf/igenomes.config
    - conf/igenomes_ignored.config
  files_unchanged:
    - .gitattributes
    - .gitignore
    - .github/PULL_REQUEST_TEMPLATE.md
    - assets/nf-core-spatialvi_logo_light.png
    - docs/images/nf-core-spatialvi_logo_light.png
    - docs/images/nf-core-spatialvi_logo_dark.png
nf_core_version: 4.0.0
repository_type: pipeline
template:
  author: Erik Fasterius, Christophe Avenel, Sergii Domanskyi, Jeffrey Chuang, Anuj
    Srivastava
  description: 10X Visium Spatial Transcriptomics
  force: false
  is_nfcore: true
  name: spatialvi
  org: nf-core
  outdir: .
  skip_features:
    - igenomes
  version: 1.0dev
